### PR TITLE
iOS Jawn Syncing

### PR DESCRIPTION
**Pull request by maxluzuriaga**
Built a system for syncing Jawns to iOS. Essentially the iOS app mirrors the state of the database on its own local SQlite store, using Core Data. This way, we can query the database much much faster, and Jawns can be loaded to the device instantly, even when there's no internet connection. Every time the app syncs with the server, it determines which Jawns are new on the server since the last sync, and which ones on the local device have been deleted from the server, and then makes those changes on the device, with appropriate animation.

Also: pull to refresh.

### CODE REVIEW

**Comment by cangevine** [comment]
This seems like a pretty big design choice -- I think it's worth talking it over before merging right away.
I remember this came up as an option when talking with Arpit this spring, and at the time his advice (and our decision) was to load everything from the web API. I'm concerned that trying to mirror the database on a local device will be unsustainable in the end if we have more than just a few users. It could be great to mirror certain users (for example, if we allow users to create groups), but otherwise I think we would be trying to mirror a _ton_ of Jawns.
Your thoughts?

**Comment by maxluzuriaga** [comment]
Hmm, I think that makes a valid point, but I should clarify that this implementation doesn't just fetch everything in the database and save it. Instead it's more like when the user tries to view x jawns, it loads them from the database, and then saves those jawns to the database, if they aren't there already. I view this as ascaching behavior, where if you're downloading the jawns from the api, why not save them to the device? This'll make the UI snappier, with very little downside (in my opinion). The same could go for when a user views an idea. Only then should the app fetch the associated sparks, tags, and comments for that idea, and if you're fetching that information, why not save it to the device for future use? Obviously then this information would be updated if the user looks at the same idea again, and something about it has changed.

The main benefit of keeping all this information is that the next time the idea is loaded, the user will have something to look at onscreen _instantly_, while the app fetches changes and updates the cache in the background, instead of waiting a potentially long time to see anything on screen.

With this model, users outside of the user's "group", for example, would never be saved to the device, because the user would never have need of accessing them, and thereby of caching them.

Just like any cache as well, this could be cleared if space on the device becomes an issue, or if a user doesn't access an idea (for example), for a very long time.

I was initially skeptical about trying to do this as well, but actually implementing some of this stuff on iOS has made it pretty clear to me that this approach has very little overhead, but comes with enormous benefits for both speed and user experience.

**Comment by aqeelphillips** [comment]
If I can chime in I think that this is a good feature that should be implemented in the (possibly near) future. But for now I'm not sure if we need to distract ourselves with the iOS app while v1 for the Note is still in development, which is the current goal

**Comment by maxluzuriaga** [comment]
Yeah of course, I definitely agree our focus should be on the Android application, this is more just my own side project which I figured should go into the repo in case anyone else wanted to check it out. By all means, we should be thinking about Android first.

**Comment by cangevine** [comment]
Great discussion here. I'm on board for all of the things you both have articulated.
Can you share any more thoughts on expiring data and removing it from the local database? If it'll essentially be acting as a cache, we should be sure to limit the size of the local database and have an intelligent way to clear out irrelevant data. 
—

**Comment by maxluzuriaga** [comment]
Well my idea for clearing out the cache would be something like this:

Whenever a Spark/Idea/User/Comment object is retrieved from the API, the local database should either save or update this object on the local cache depending on if the object already exists in the cache, and at this time, some date attribute on the object (like "updated_date") should be set to the current time. Then, every time the app is opened, it could run a query to find and purge every object in the cache with an "updated_date" before 30 days ago (or some time period like this). If the user is particularly active on the app, and manages to save a cache of too many objects, the app could just do something like order all the cached objects based on their updated date, and then delete the last half of them (or something like this).

We could also provide some sort of "clear_cache" attribute for JSON responses in the API that, when present, would trigger the app to clear its entire cache. This would be useful if we changed a model on the database side, making any caches using the old model invalid.

These are just a few ideas, but I really think that, for iOS at least, given how easy it is to set up a lightning-fast SQLite-backed cache locally, this is really the best solution. Of course this is not an essential feature for STEAMnet, so if the cost of setting up something like this on Android is too great right now, then it definitely should not be a priority. I would still argue that caching like this is a fairly essential part of a polished mobile application, but of course it should take a backseat to actually implementing the features of STEAMnet that make it STEAMnet (or Flynt I guess, i'm still not sure where we landed on that).

**Pull request merged**
