### PR TITLE
Functionality for Ideas Controller, Jawns Controller, many more tests

### PR DESCRIPTION
**Pull request by maxluzuriaga**
Ideas controller now makes sure the API call passes in a valid lists of sparks before creating a new idea. Also made the "delete" functionality mirror that of a Spark (instead of deleting the idea, it simply destroys the relationship between the user making the call and the idea.)

Added tests for these new features and the rest of IdeasController's functionality.

Also added tests for the Idea model. (Up to 111 test cases now!)

### CODE REVIEW

**Comment by maxluzuriaga** [comment]
Just added commits which adds filtering to the jawns controller. To do this, simple specify the `filter` attribute during a request to `/api/v1/jawns.json`, in the form `/api/v1/jawns.json?filter=ideas` or `/api/v1/jawns.json?filter=sparks`. These request will return only ideas and only sparks, respectively. You can still provide the `limit` attribute on these requests to only take the most recent n sparks, or most recent n ideas.

Also added tests to `jawns_controller_spec.rb` to test this new functionality.

**Comment by cangevine** [comment]
Nice update again, Max. Once all users have been removed from a Spark/ Idea, should the front-end be responsible for saying that it was created by "Anonymous" or something along those lines?

Also -- it seems as if there have been enough changes at this point to justify updating the README.md. Would you mind updating that with your next pull request?

**Comment by maxluzuriaga** [comment]
Yeah, I think that's the functionality we should be looking for on the front end. The only question is how multiple users should be handled for Ideas.

Right now an Idea should only every have 1 user, because I did not write any code to add other users to an already created idea. This is only because I don't really know how to handle this, or if this is even something we want. I think for Ideas this concept makes less sense than for Sparks, because an idea would need to have the same sparks, and exact same description to be accurately considered "the same idea."

I think that this is such an unlikely event, and if it were to occur the functionality would be so jarring to users that I think it makes a lot more sense to just change the relationship between Ideas and Users to be a simple "each Idea has only one user" relationship. This is definitely a question for the group though.

I definitely agree, the readme is way out of date, I'll update it when I get a chance.

**Comment by cangevine** [comment]
I'm on board, Max. Having one user per idea sounds like the right fit, but
multiple (potential) users per spark is what we need too.

**Comment by maxluzuriaga** [comment]
Okay, I can write a migration to easily switch over the current databases to this new system.

**Pull request merged**
